/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Form;

import controller.DetailController;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Time;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import model.Detail;
import model.ManagermentPersonalModel;
import model.ModalDetail;
import model.MyTime;
import model.Saff;
import ultil.Convert;
import ultil.Fomart;
import ultil.ImageCustom;
import ultil.List;
import ultil.Message;
import ultil.Validate;

/**
 *
 * @author PC
 */
public class DetailFrom extends javax.swing.JFrame {

    private Saff personal;
    private Detail detail;
    private ModalDetail model = new ModalDetail();
    int begin = 0;
    int finish = 0;
    private byte[] personImage = null;
    private ManagermentPersonalModel modelPersonal = new ManagermentPersonalModel();
    private MainFrom main;
//    private MainFrom mainFrom = new MainFrom();

    /**
     * Creates new form DetailFrom
     */
    public DetailFrom() {
        initComponents();
//        action();
        detail = new Detail("NV001", new Time(17, 0, 0), new Time(21, 00, 00), 10, 20, 30, 50);
        initCboTime();
        showDetail();

    }

    public DetailFrom(Saff personal, MainFrom main) {
        initComponents();
        this.personal = personal;
        this.main = main;
        action();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtIdPerson = new javax.swing.JTextField();
        txtAddressPerson = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        lblIdPerson = new javax.swing.JLabel();
        lblAddressPerson = new javax.swing.JLabel();
        txtNamePerson = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblNamePerson = new javax.swing.JLabel();
        txtBirthPerson = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblBirthPerson = new javax.swing.JLabel();
        cboFemalePerson = new javax.swing.JRadioButton();
        cboOtherPerson = new javax.swing.JRadioButton();
        lblRolePerson = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        cboManagerPerson = new javax.swing.JRadioButton();
        cboPerson = new javax.swing.JRadioButton();
        cboCashierPerson = new javax.swing.JRadioButton();
        txtEmailPerson = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblEmailPerson = new javax.swing.JLabel();
        lblGentherPerson = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        cboMalePerson = new javax.swing.JRadioButton();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel21 = new javax.swing.JPanel();
        lblImagePeson = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIdPerson1 = new javax.swing.JLabel();
        cboBegin = new javax.swing.JComboBox<>();
        lblIdPerson2 = new javax.swing.JLabel();
        cboFinish = new javax.swing.JComboBox<>();
        txtDay = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        lblAddressPerson1 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        lblAddressPerson2 = new javax.swing.JLabel();
        txtBonus = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        lblAddressPerson3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        lblAddressPerson4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnTotal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 247, 220));

        txtIdPerson.setBackground(new java.awt.Color(254, 247, 220));
        txtIdPerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtIdPerson.setText("ID");
        txtIdPerson.setBorder(null);

        txtAddressPerson.setBackground(new java.awt.Color(254, 247, 220));
        txtAddressPerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtAddressPerson.setText("Address");
        txtAddressPerson.setBorder(null);

        lblIdPerson.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblIdPerson.setText("Begin Time");

        lblAddressPerson.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblAddressPerson.setText("Address");

        txtNamePerson.setBackground(new java.awt.Color(254, 247, 220));
        txtNamePerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNamePerson.setText("Name");
        txtNamePerson.setBorder(null);

        lblNamePerson.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblNamePerson.setText("Name");

        txtBirthPerson.setBackground(new java.awt.Color(254, 247, 220));
        txtBirthPerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtBirthPerson.setText("Birth");
        txtBirthPerson.setBorder(null);

        lblBirthPerson.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblBirthPerson.setText("Birth");

        cboFemalePerson.setBackground(new java.awt.Color(254, 247, 220));
        buttonGroup1.add(cboFemalePerson);
        cboFemalePerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        cboFemalePerson.setText("Female");
        cboFemalePerson.setFocusPainted(false);

        cboOtherPerson.setBackground(new java.awt.Color(254, 247, 220));
        buttonGroup1.add(cboOtherPerson);
        cboOtherPerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        cboOtherPerson.setText("Other");
        cboOtherPerson.setFocusPainted(false);

        lblRolePerson.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblRolePerson.setText("Role");

        cboManagerPerson.setBackground(new java.awt.Color(254, 247, 220));
        buttonGroup2.add(cboManagerPerson);
        cboManagerPerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        cboManagerPerson.setText("Manager");
        cboManagerPerson.setFocusPainted(false);

        cboPerson.setBackground(new java.awt.Color(254, 247, 220));
        buttonGroup2.add(cboPerson);
        cboPerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        cboPerson.setText("Personal");
        cboPerson.setFocusPainted(false);

        cboCashierPerson.setBackground(new java.awt.Color(254, 247, 220));
        buttonGroup2.add(cboCashierPerson);
        cboCashierPerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        cboCashierPerson.setText("Cashier");
        cboCashierPerson.setFocusPainted(false);

        txtEmailPerson.setBackground(new java.awt.Color(254, 247, 220));
        txtEmailPerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtEmailPerson.setText("Email");
        txtEmailPerson.setBorder(null);

        lblEmailPerson.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblEmailPerson.setText("Email");

        lblGentherPerson.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblGentherPerson.setText("Genther");

        cboMalePerson.setBackground(new java.awt.Color(254, 247, 220));
        buttonGroup1.add(cboMalePerson);
        cboMalePerson.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        cboMalePerson.setText("Male");
        cboMalePerson.setFocusPainted(false);
        cboMalePerson.setVerifyInputWhenFocusTarget(false);

        jPanel21.setBackground(new java.awt.Color(254, 247, 220));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblImagePeson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagePeson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Icon/icons8_person_100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagePeson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagePeson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("STXinwei", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Detail");

        lblIdPerson1.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblIdPerson1.setText("ID");

        cboBegin.setBackground(new java.awt.Color(254, 247, 220));
        cboBegin.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N

        lblIdPerson2.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblIdPerson2.setText("Finish Time");

        cboFinish.setBackground(new java.awt.Color(254, 247, 220));
        cboFinish.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N

        txtDay.setBackground(new java.awt.Color(254, 247, 220));
        txtDay.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtDay.setText("0");
        txtDay.setBorder(null);

        lblAddressPerson1.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblAddressPerson1.setText("Day Of Week");

        txtSalary.setBackground(new java.awt.Color(254, 247, 220));
        txtSalary.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtSalary.setText("0");
        txtSalary.setBorder(null);

        lblAddressPerson2.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblAddressPerson2.setText("Salary Of Hour");

        txtBonus.setBackground(new java.awt.Color(254, 247, 220));
        txtBonus.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtBonus.setText("0");
        txtBonus.setBorder(null);

        lblAddressPerson3.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblAddressPerson3.setText("Bonus");

        txtTotal.setBackground(new java.awt.Color(254, 247, 220));
        txtTotal.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtTotal.setText("0");
        txtTotal.setBorder(null);
        txtTotal.setEnabled(false);

        lblAddressPerson4.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        lblAddressPerson4.setText("Total");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnUpdate.setBackground(new java.awt.Color(254, 247, 220));
        btnUpdate.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorderPainted(false);
        btnUpdate.setFocusPainted(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnTotal.setBackground(new java.awt.Color(254, 247, 220));
        btnTotal.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.setBorderPainted(false);
        btnTotal.setFocusPainted(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnImage.setBackground(new java.awt.Color(254, 247, 220));
        btnImage.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnImage.setText("Image");
        btnImage.setBorderPainted(false);
        btnImage.setFocusPainted(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIdPerson1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdPerson)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamePerson)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBirthPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBirthPerson)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRolePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboManagerPerson)
                                .addGap(39, 39, 39)
                                .addComponent(cboPerson)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboCashierPerson))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEmailPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmailPerson)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGentherPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboMalePerson)
                                .addGap(62, 62, 62)
                                .addComponent(cboFemalePerson)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboOtherPerson))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(104, 104, 104)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAddressPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator15)
                            .addComponent(txtAddressPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(776, 776, 776)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIdPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAddressPerson3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdPerson2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(cboFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBonus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)))))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddressPerson2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblAddressPerson1))
                            .addComponent(lblAddressPerson4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdPerson1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBirthPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBirthPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGentherPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMalePerson)
                            .addComponent(cboFemalePerson)
                            .addComponent(cboOtherPerson))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRolePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboManagerPerson)
                            .addComponent(cboPerson)
                            .addComponent(cboCashierPerson))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAddressPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddressPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIdPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAddressPerson1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAddressPerson2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIdPerson2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAddressPerson3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal)
                            .addComponent(lblAddressPerson4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboBegin;
    private javax.swing.JRadioButton cboCashierPerson;
    private javax.swing.JRadioButton cboFemalePerson;
    private javax.swing.JComboBox<String> cboFinish;
    private javax.swing.JRadioButton cboMalePerson;
    private javax.swing.JRadioButton cboManagerPerson;
    private javax.swing.JRadioButton cboOtherPerson;
    private javax.swing.JRadioButton cboPerson;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAddressPerson;
    private javax.swing.JLabel lblAddressPerson1;
    private javax.swing.JLabel lblAddressPerson2;
    private javax.swing.JLabel lblAddressPerson3;
    private javax.swing.JLabel lblAddressPerson4;
    private javax.swing.JLabel lblBirthPerson;
    private javax.swing.JLabel lblEmailPerson;
    private javax.swing.JLabel lblGentherPerson;
    private javax.swing.JLabel lblIdPerson;
    private javax.swing.JLabel lblIdPerson1;
    private javax.swing.JLabel lblIdPerson2;
    private javax.swing.JLabel lblImagePeson;
    private javax.swing.JLabel lblNamePerson;
    private javax.swing.JLabel lblRolePerson;
    private javax.swing.JTextField txtAddressPerson;
    private javax.swing.JTextField txtBirthPerson;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtEmailPerson;
    private javax.swing.JTextField txtIdPerson;
    private javax.swing.JTextField txtNamePerson;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private DetailController controller = new DetailController(this);

    public void init() {
        initCboTime();
        showPerson(personal);
        initDetail();
        showDetail();
    }

    public void action() {
        this.addWindowListener(controller);
        btnUpdate.addActionListener(controller);
        btnTotal.addActionListener(controller);
        btnImage.addActionListener(controller);
    }

    public void showPerson(Saff p) {
        try {
            txtIdPerson.setText(p.getIdSaff());
            txtNamePerson.setText(p.getNameSaff());
            txtBirthPerson.setText(Fomart.parseDate(p.getDateOfBirth()));
            txtEmailPerson.setText(p.getEmail());
            txtAddressPerson.setText(p.getAddress());

            String genther = p.getGenther();
            String role = p.getRole();

            if (role.equals(cboManagerPerson.getText())) {
                cboManagerPerson.setSelected(true);
            } else if (role.equals(cboPerson.getText())) {
                cboPerson.setSelected(true);
            } else {
                cboCashierPerson.setSelected(true);
            }

            if (genther.equals(cboMalePerson.getText())) {
                cboMalePerson.setSelected(true);
            } else if (genther.equals(cboFemalePerson.getText())) {
                cboFemalePerson.setSelected(true);
            } else {
                cboOtherPerson.setSelected(true);
            }

            //image
            if (p.getImage() != null) {
                try {
                    Image img = ImageCustom.createImageFromByteArray(p.getImage(), "jpg");
                    lblImagePeson.setIcon(new ImageIcon(img));
                } catch (IOException ex) {
                    Message.showWarning(ex.getMessage(), this);
                }
            } else {
                ImageIcon icon = new ImageIcon(getClass().getResource("/view/Icon/icons8_person_100px.png"));

                lblImagePeson.setIcon(icon);
            }
        } catch (Exception e) {
            txtBirthPerson.setText("1/1/2000");
        }
    }

    public void initCboTime() {
        ArrayList<MyTime> list = List.getListTime();
        for (MyTime time : list) {
            cboBegin.addItem(time.getTime().toString());
            cboFinish.addItem(time.getTime().toString());
        }
    }

    public void initDetail() {
        this.detail = model.getDetail(personal.getIdSaff());
    }

    public void updateTime() {
        begin = List.getListTime().get(cboBegin.getSelectedIndex()).getTimeNumber();
        finish = List.getListTime().get(cboFinish.getSelectedIndex()).getTimeNumber();
    }

    public Double total() {
        double total = 0;
        try {
            updateTime();
            int fainalTime = finish - begin;
            double salaryOfHour = Convert.convertDouble(txtSalary.getText());
            double day = Convert.convertDouble(txtDay.getText());
            double bonus = Convert.convertDouble(txtBonus.getText());

            total = fainalTime * salaryOfHour * day + bonus;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return total;
    }

    public void showDetail() {
        if (detail != null) {
            cboBegin.setSelectedItem(detail.getBeginTime().toString());
            cboFinish.setSelectedItem(detail.getFinishTime().toString());
            txtBonus.setText(detail.getBonus() + "");
            txtDay.setText(detail.getDayOfWeef() + "");
            txtSalary.setText(detail.getSalaryOfHour() + "");
            txtTotal.setText(detail.getTotal() + "");

        }
    }

    public Detail createDetail() {
        Detail dt = null;
        try {
            if (total() <= 0) {
                Message.showWarning("Total invalid !", this);
                return null;
            }
            dt = new Detail();
            dt.setIdSaff(txtIdPerson.getText());
            dt.setBeginTime(List.getListTime().get(cboBegin.getSelectedIndex()).getTime());
            dt.setFinishTime(List.getListTime().get(cboFinish.getSelectedIndex()).getTime());
            dt.setDayOfWeef(Convert.convertInt(txtDay.getText()));
            dt.setBonus(Convert.convertFloat(txtBonus.getText()));
            dt.setSalaryOfHour(Convert.convertFloat(txtSalary.getText()));
            dt.setTotal(total());
        } catch (Exception e) {
            e.printStackTrace();
        }

        return dt;
    }

    public void handleBtnUpdate() {
        updateTime();
        if (Validate.validateDetail(txtDay, txtSalary, txtBonus, begin, finish, this)) {

            Detail dtc = model.getDetail(personal.getIdSaff());
            Detail dt = createDetail();
            Saff us = createPerson();
            boolean p = modelPersonal.update(us);

            if (p) {
                main.renderPersonal(modelPersonal.getList());
            }
            if (dtc == null) {
                txtTotal.setText(total() + "");
                boolean i = model.insert(dt);

                if (i) {
                    Message.showSuccess("Update successfuly !", this);
                } else {
                    Message.showWarning("Update fail !", this);

                }
            } else {
                if (dt != null) {
                    txtTotal.setText(total() + "");
                    boolean i = model.update(dt);
                    if (i) {
                        Message.showSuccess("Update successfuly !", this);
                    } else {
                        Message.showWarning("Update fail !", this);

                    }
                }
            }
        }
    }

    public void handleTotal() {
        updateTime();
        if (Validate.validateDetail(txtDay, txtSalary, txtBonus, begin, finish, this)) {
            txtTotal.setText(total() + "");
        }
    }

    public void handleImagePerson() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".jpg");
                }
            }

            @Override
            public String getDescription() {
                return "Image file (*.jpg)";
            }
        });

        if (chooser.showOpenDialog(this) == JFileChooser.CANCEL_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();
        try {
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = ImageCustom.resize(icon.getImage(), 200, 200);
            ImageIcon resizedIcon = new ImageIcon(img);
            lblImagePeson.setIcon(resizedIcon);
            personImage = ImageCustom.toByteArray(img, "jpg");
        } catch (Exception e) {
            Message.showWarning(e.getMessage(), this);
        }
    }

    // create Person from field
    public Saff createPerson() {
        Saff p = new Saff();

        try {

            p.setIdSaff(txtIdPerson.getText());
            p.setNameSaff(txtNamePerson.getText());
            p.setDateOfBirth(Fomart.convertDate(txtBirthPerson.getText()));
            p.setEmail(txtEmailPerson.getText());
            p.setAddress(txtAddressPerson.getText());

            // genther
            if (cboFemalePerson.isSelected()) {
                p.setGenther(cboFemalePerson.getText());
            } else if (cboMalePerson.isSelected()) {
                p.setGenther(cboMalePerson.getText());
            } else {
                p.setGenther(cboOtherPerson.getText());
            }

            // role
            if (cboManagerPerson.isSelected()) {
                p.setRole(cboManagerPerson.getText());
            } else if (cboPerson.isSelected()) {
                p.setRole(cboPerson.getText());
            } else {
                p.setRole(cboCashierPerson.getText());
            }

            // image
            p.setImage(personImage);
        } catch (Exception e) {
            Message.showWarning(e.getMessage(), this);
        }
        return p;
    }

    //    //update personal
    public void updatePerson() {

    }
}
